services:

#  db:
#    image: "postgres:16.2-bullseye"
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASS}
#      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - db_data:/var/lib/postgresql/data
#
#    ports:
#      - "5432:5432"

  python:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python rtf_tube/manage.py migrate && 
               python rtf_tube/manage.py collectstatic &&
               python rtf_tube/manage.py runserver"
    ports:
      - "8001:8000"
#    depends_on:
#      - db
#
#volumes:
#  db_data:
#  static_volume:

