services:

#  db:
#    image: "postgres:16.2-bullseye"
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASS}
#      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - db_data:/var/lib/postgresql/data
#
#    ports:
#      - "5432:5432"

  django:
    build: .
    command: sh -c "python rtf_tube/manage.py migrate && 
               python rtf_tube/manage.py collectstatic --noinput &&
               python rtf_tube/manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"

  preview_consumer:
    build: .
    command: sh -c "python rtf_tube/manage.py preview_updater_consumer"

  preview_scheduler:
    build: .
    command: sh -c "python rtf_tube/manage.py preview_updater_scheduler"

#    depends_on:
#      - db
#
#volumes:
#  db_data:
#  static_volume:

