# Generated by Django 4.1.7 on 2023-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_preview_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to='', verbose_name='Превью'),
        ),
    ]
