# Generated by Django 4.1.7 on 2023-03-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0004_alter_video_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.ImageField(
                upload_to="video/static/video/preview", verbose_name="Превью"
            ),
        ),
    ]
