# Generated by Django 4.1.7 on 2023-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_alter_video_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="author_id",
            field=models.IntegerField(default=2, verbose_name="ID автора"),
            preserve_default=False,
        ),
    ]
