# Generated by Django 4.1.7 on 2023-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0009_alter_video_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.ImageField(
                default="video/static/video/preview/v_review.jpg",
                upload_to="video/static/video/preview",
                verbose_name="Превью",
            ),
        ),
    ]
