# Generated by Django 4.1.7 on 2023-03-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0014_comment_alter_video_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="comments",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="video.comment",
            ),
        ),
    ]
