# Generated by Django 4.1.7 on 2023-04-14 17:56

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0022_alter_video_preview_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.ImageField(
                upload_to="video/preview",
                validators=[
                    video.validators.validate_image_extension,
                    video.validators.file_size,
                ],
                verbose_name="Превью",
            ),
        ),
    ]
