# Generated by Django 4.2 on 2023-04-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_alter_video_options_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
